### ISSUE TITLE
Model protocol and database schema mismatch

### ISSUE THREAD

**Issue by johankool** [qutheory/fluent-example#2]
The Model protocol has id as a String, but in the SQL statement to create the table id is an INTEGER.

So running example gives:

`[SQL] UPDATE `users` SET `name` = 'Test'' WHERE  `id` = '1'
Query error 1 for statement 'UPDATE `users` SET `name` = 'Test'' WHERE  `id` = '1';' error Optional("near \"1\": syntax error")`

**Comment by tanner0101** [comment]
It looks like there is an error with the `''` after `Test`. 

@artkay do you think submitting the primary key as a string should create any issues?

**Comment by artkay** [comment]
Depends on the type of the column. I'm not that familiar with SQLite, MySQL converting it by itself so something like 

``` SQL
select * from countries where id = '1';
```

works perfectly fine. In the given example I'd expect to trouble to come from the extra quote there: `'Test''`

**Comment by johankool** [comment]
There is indeed an extra ' in the sample code: `"Test'"`. So seems to be caused by not properly escaping the input.

**Comment by tanner0101** [comment]
Fixed here.

https://github.com/tannernelson/fluent-example/commit/12081e08d0596485b0c38a320745f39898e00285

**Comment by johankool** [comment]
Hm, sorta fixed only. This shouldn't trip over a quote character obviously. But besides that, to go back to my actual question, is it intentional that the id in the Model is a String and not an Int?

**Comment by tanner0101** [comment]
> is it intentional that the id in the Model is a String and not an Int?

Everything comes back from the C SQLite lib as a String. So that mapping makes the most sense from a technical standpoint. I'm going to work on mapping it to an `Int`, though. 

>  This shouldn't trip over a quote character obviously.

Escaping the input is top on the todo list right now. This project is still very much a WIP.
