### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by kaandedeoglu** [qutheory/fluent-example#4]
I'm getting the error on launch.

`Could not initialize driver: connection("library routine called out of sequence")`

I've created the example table in the `Database` folder. Any ideas why this might be happening?

**Comment by Joannis** [comment]
Doesn't seem like a Fluent issue. Seems like an issue with the driver.

EDIT: Based on the fact that I can't find this error anywhere in Fluent

**Comment by kaandedeoglu** [comment]
@Joannis Yes, putting a breakpoint revealed that the error is actually being generated in the driver. The error message is coming from sqlite3 itself.

**Comment by tanner0101** [comment]
@kaandedeoglu I think this error is coming from Fluent not being able to find your database. Are you using Xcode? If so, make sure to set the correct working directory.

**Comment by tanner0101** [comment]
I just fixed a bug that I think is causing that misleading error message 

https://github.com/qutheory/fluent-sqlite/commit/bd4e248664a1240ced109f1c383d751f5ee46f5b

Try cleaning your project and building again @kaandedeoglu

**Comment by kaandedeoglu** [comment]
Thanks for the quick reply, i'm no longer getting the same error message 👍 💯
